#!/bin/bash --noprofile
export File=${HOME}/.config/l2tpUSER
export Env=/run/RTI_VPN
export B24=npodr.bitrix24.ru
export nmcliFile=/etc/NetworkManager/system-connections/RTI_VPN
f_help(){              #   Мини help
grep '^f_.*()' /usr/local/bin/RTI_VPN
cat <<EOL
###############################################################
#  DESC:   RTI_VPN c генерацией одноразового пароля
###############################################################
Инструкция по подключению к сети предприятия внешних устройств через веб-портал:
   https://npodr.bitrix24.ru/workgroups/group/4/tasks/task/view/14806/?MID=145538&any=group%2F4%2Ftasks%2Ftask%2Fview%2F14806%2F
Для получения QR кода перейдите по ссылке:
   https://auth.aorti.ru:8043/cps/totp?token=Mjow  # в сети предприятия
   https://sslvpn.npodr.ru:10443                   # из вне
Зайдите под своим сетевым аккаунтом c указанием домена, например:
   vbulov@aorti.ru
Запомните код доступа вида:
   xxxx yyyy zzzz vvvv
Если QR код не появляется и система пишет ошибку:
   - QR код уже выдан
   - У Вас нет прав на удалённый доступ
Обратитесь в тех поддержку:
   e-Mail: support@npodr.ru
   Тел.:   3000,(495)612-0331
Запуск RTI_VPN при установленном VPN соединении его деактивирует
Добавлен маршрут для npodr.bitrix24.ru минуя VPN
Настроить  keepass2
   Tools->Options->Integration->"URL Overrides..."->Add
   Scheme:         RTI_VPN
   URL Overrides:  cmd:///bin/bash -c "RTI_VPN <<<{PASSWORD}"
   Edit->Add Entry
   Password:       "Ваш корпоративный пароль"
   URL:            RTI_VPN://
Для fedora
   dnf remove -y libreswan ; dnf install -y strongswan
###############################################################
#  АО РТИ им.Академика А.Л.Минца
#      2023/03/31  Кузнецов М.В. <MKuznetsov@rti-mints.ru> ver1.0
#      2023/12/21  Булов B.Г.    <V.Bulov@gmail.com>       ver2.3
#      2024/12/08  Булов B.Г.    <V.Bulov@gmail.com>       ver3.0
#      2025/01/06  Булов B.Г.    <V.Bulov@gmail.com>       ver3.1
###############################################################
EOL
}  ############################################################
trap "sleep 1;sudo RTI_VPN disconnect;exit" QUIT INT STOP TERM
   ############################################################
f_ln(){                #   Link на ярлык
[ ! -L /etc/skel/Desktop/$1.desktop ] && ln -s /usr/local/Desktop/$1.desktop /etc/skel/Desktop/$1.desktop
ls -d /home/*/Desktop|xargs -I '{}' sh -c "[ ! -h {}/$1.desktop ] && ln -s /usr/local/Desktop/$1.desktop {}/$1.desktop"
}  ############################################################
f_disconnect(){        #   Удалить RTI_VPN туннель
   [[ -f ${nmcliFile} ]] && {
       # echo "Удаляем RTI_VPN туннель"
       rm -f ${nmcliFile}
       nmcli c reload
   }
   rm -f ${Env}
   sed -i /${B24}/d /etc/hosts
}  ############################################################
f_create(){            #   Настроить персоональный RTI_VPN туннель
l2tpUSER=${1:-${SUDO_USER}}
usermod -a -G netdev  ${l2tpUSER}
cat >${nmcliFile} <<EOL
[connection]
id=RTI_VPN
type=vpn
autoconnect=false
permissions=user:${l2tpUSER}:;

[vpn]
gateway=sslvpn.npodr.ru
ipsec-enabled=yes
ipsec-esp=aes128-sha1!
ipsec-ike=aes128-sha1-modp1024!
ipsec-psk=6129999
mru=1400
mtu=1400
no-vj-comp=yes
noaccomp=yes
nobsdcomp=yes
nodeflate=yes
nopcomp=yes
password-flags=0
refuse-chap=yes
refuse-eap=yes
refuse-mschap=yes
refuse-mschapv2=yes
user=${l2tpUSER}@aorti.ru
service-type=org.freedesktop.NetworkManager.l2tp

[ipv4]
dns-search=aorti.ru
dns=172.28.237.135;172.28.237.128
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
ip6-privacy=0
method=ignore

[proxy]
method=1
EOL
chmod 0600 ${nmcliFile}
}  ############################################################
f_RPA(){               #   Запросы на активизацию RTI_VPN_RPA туннеля
   nmcli -f NAME con show --active 2>/dev/null | grep -q RTI_VPN
   (( 0 == $? )) &&  exit 0
   nc -zvw3 sslvpn.npodr.ru 10443 2>/dev/null
   (( 0 != $?  )) && { echo "Not connect https:sslvpn.npodr.ru:10443" ; exit 0 ;}
   [[ -f ${Env} ]] && source ${Env}
   f_nmcli $(base64 -d <<<${l2tpUSER} ) <<< "$(base64 -d <<<${Password} ) $(base64 -d <<<${key} )"
   (( 0 == $? )) &&  {
      sed -i "/Not connect/d" ${Env}
      exit 0
   }
   [[ -f ${Env} ]] && {
      echo "#Not connect" >> ${Env}
      (( 7 <  $(wc -l < ${Env}) )) && rm -f ${Env}
   }
}  ############################################################
f_connect(){           #   Запросы на активизацию RTI_VPN туннеля
if [ ! -f ${File} ] ; then
   cat << EOL
   Для получения QR кода перейдите по ссылке:
       https://auth.aorti.ru:8043/cps/totp?token=Mjow  # в сети предприятия
       https://sslvpn.npodr.ru:10443                   # из вне
EOL
   printf "\r  [ \033[0;33m?\033[0m ] Введите Ваш уникальный ключ от UserGate: "
   read  key
   key=$(tr -d ' ' <<< $key)
   #echo ${key}
   base64      <<< ${key} > ${File}
else
   key=$(base64 -d < ${File} )
fi
#echo ${key}
unset Password
if read -t 0 ; then        # Вызов из keepass
   read Password
else
   prompt="Введите Ваш корпоративный пароль: "
   while IFS= read -p "$prompt" -r -s -n 1 char ;do
      [[ $char == $'\0' ]] && break
      prompt='*'
      Password+="$char"
   done
fi
sudo RTI_VPN disconnect
echo
sudo RTI_VPN nmcli ${USER} <<< "${Password} ${key}"
(( 0 != $? )) && {
cat <<EOL
   Возможные причины:
   - Неправильно ввели QR код
   - Неправильно ввели пароль
   - Вы не в группе l2tp на  UserGate
   - Заблокирована Ваша сессия на UserGate
   - Оператор телефонной сети обрывает VPN
EOL
   [[ "_  Normal" != "_ $(chronyc tracking | awk -F: '/Leap status/ {print $2}')" ]] && echo -e "   - Ошибка синхронизации времени <<<chronyc tracking>>>\n"
   systemctl status xl2tpd &> /dev/null
   (( 0 != $? )) && echo -e "   - xl2tpd не запущен (systemctl status xl2tpd )\n"
   nc -zvw3 sslvpn.npodr.ru 10443 2>/dev/null
   (( 0 != $? )) && echo -e "   - Не отвечает https:sslvpn.npodr.ru:10443\n"
   sudo RTI_VPN disconnect
   sleep 7
   return
}
kinit ${USER} <<< "$Password"        # Получить билет для работы по керберос
}  ############################################################
f_nmcli(){             #   Активизировать RTI_VPN туннель
   declare int i=2 t=0
   read Password key
   #echo "<<<${Password}|${1}|${key}|${USER}|${SUDO_USER}>>>"
   [[ ! -f ${Env} && -n ${SUDO_USER} ]] && { printf "l2tpUSER=%s\nkey=%s\nPassword=%s\n" $(base64 <<<${1}) $(base64 <<<${key}) $(base64 <<<${Password}) >${Env} ; chmod 0600 ${Env} ;}
   IPD=$(ip r | awk '/default/ {print $3}')
   IPB=$(ping -c1 -w3 ${B24} | awk -F'[( )]' '/PING/ { print $4}')
   f_create $1
   nmcli con re
   while (( i-- > 0 )) ; do
       t=$(($(date +%_S) % 30));(( 7 > $t )) && sleep $(( 7 - $t ))
       nmcli con modify RTI_VPN vpn.secrets password=${Password}:$(oathtool -b --totp ${key})
       nmcli con up RTI_VPN
       (( 0 == $? )) && {
           [[ "_${IPB}" =~ _[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}  ]] && {
               ip route | grep -q "${IPB} via ${IPD}"
               (( 0 != $? )) && ip route add ${IPB} via ${IPD}
               sed -i /${B24}/d /etc/hosts
               echo "${IPB} ${B24}" >> /etc/hosts
           }
           return 0
       }
   done
   return 1
}  ############################################################
f_clear(){             #   Удалить хранилище уникального ключа от UserGate
   rm -f ${File} ${Env}
}  ############################################################
f_install(){           #   Установка SUDO и ярлыка desktop => sudo RTI_VPN install
[ ! -f /etc/sudoers.d/RTI_VPN ] && echo "ALL ALL=(ALL:ALL) NOPASSWD: /usr/local/bin/RTI_VPN" >/etc/sudoers.d/RTI_VPN
cat >/usr/local/Desktop/RTI_VPN.desktop <<EOL
[Desktop Entry]
Name=Доступ RTI_VPN
Name[ru]=Доступ RTI_VPN
Type=Application
NoDisplay=false
Exec=/usr/local/bin/RTI_VPN
Icon=security-policy
Icon[ru]=security-policy
Hidden=false
Path=/usr/local/bin/RTI_VPN
Terminal=true
StartupNotify=false
EOL
   f_ln RTI_VPN
}  ############################################################
f=$1
(( 0 != $# )) && { shift ; f_${f} "$@" ; exit ;}
nmcli -f NAME con show --active | grep -q RTI_VPN
(( $? == 0 )) && { sudo RTI_VPN disconnect; exit 0 ; }
f_connect
