#!/bin/bash --noprofile
export File=${HOME}/.config/l2tpUSER
f_help(){              #   Мини help
grep '^f_.*()' /usr/local/bin/RTI_VPN
cat <<EOL
###############################################################
#  DESC:   RTI_VPN c генерацией одноразового пароля
###############################################################
Инструкция по подключению к сети предприятия внешних устройств через веб-портал:
   https://npodr.bitrix24.ru/workgroups/group/4/tasks/task/view/14806/?MID=145538&any=group%2F4%2Ftasks%2Ftask%2Fview%2F14806%2F
Для получения QR кода перейдите по ссылке:
   https://auth.aorti.ru:8043/cps/totp?token=Mjow  # в сети предприятия
   https://sslvpn.npodr.ru:10443                   # из вне
Зайдите под своим сетевым аккаунтом c указанием домена, например:
   vbulov@aorti.ru
Запомните код доступа вида:
   xxxx yyyy zzzz vvvv
Если QR код не появляется и система пишет ошибку:
   - QR код уже выдан
   - У Вас нет прав на удалённый доступ
Обратитесь в тех поддержку:
   e-Mail: support@npodr.ru
   Тел.:   3000,(495)612-0331
Запуск RTI_VPN при установленном VPN соединении его деактивирует
Настроить  keepass2
   Tools->Options->Integration->"URL Overrides..."->Add
   Scheme:         RTI_VPN
   URL Overrides:  cmd:///bin/bash -c "RTI_VPN <<<{PASSWORD}"
   Edit->Add Entry
   Password:       "Ваш корпоративный пароль"
   URL:            RTI_VPN://
###############################################################
#  АО РТИ им.Академика А.Л.Минца
#      2023/03/31  Кузнецов М.В. <MKuznetsov@rti-mints.ru> ver1.0
#      2023/12/21  Булов B.Г.    <V.Bulov@gmail.com>       ver2.3
###############################################################
EOL
}  ############################################################
export nmcliFile=/etc/NetworkManager/system-connections/RTI_VPN
trap "sleep 1;sudo RTI_VPN disconnect;exit" QUIT INT STOP TERM
   ############################################################
f_ln(){                #   Link на ярлык
[ ! -L /etc/skel/Desktop/$1.desktop ] && ln -s /usr/local/Desktop/$1.desktop /etc/skel/Desktop/$1.desktop
ls -d /home/*/Desktop|xargs -I '{}' sh -c "[ ! -h {}/$1.desktop ] && ln -s /usr/local/Desktop/$1.desktop {}/$1.desktop"
}  ############################################################
f_disconnect(){        #   Удалить RTI_VPN туннель
   [ -f ${nmcliFile} ] && {
       echo "Удаляем RTI_VPN туннель"
       rm -f ${nmcliFile}
       nmcli c reload
   }
}  ############################################################
f_create(){            #   Настроить персоональный RTI_VPN туннель
export l2tpUSER=${SUDO_USER}
cat >${nmcliFile} <<EOL
[connection]
id=RTI_VPN
type=vpn
autoconnect=false
permissions=user:${l2tpUSER}:;

[vpn]
gateway=sslvpn.npodr.ru
ipsec-enabled=yes
ipsec-esp=aes128-sha1!
ipsec-ike=aes128-sha1-modp1024!
ipsec-psk=6129999
mru=1400
mtu=1400
no-vj-comp=yes
noaccomp=yes
nobsdcomp=yes
nodeflate=yes
nopcomp=yes
password-flags=2
refuse-chap=yes
refuse-eap=yes
refuse-mschap=yes
refuse-mschapv2=yes
user=${l2tpUSER}@aorti.ru
service-type=org.freedesktop.NetworkManager.l2tp

[ipv4]
dns-search=aorti.ru
dns=172.28.237.135;172.28.237.128
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
ip6-privacy=0
method=ignore

[proxy]
method=1
EOL
chmod 0600 ${nmcliFile}
nmcli c re
}  ############################################################
f_connect(){           #   Запросы на активизацию RTI_VPN туннеля
sudo RTI_VPN create
if [ ! -f ${File} ] ; then
   cat << EOL
   Для получения QR кода перейдите по ссылке:
       https://auth.aorti.ru:8043/cps/totp?token=Mjow  # в сети предприятия
       https://sslvpn.npodr.ru:10443                   # из вне
EOL
   printf "\r  [ \033[0;33m?\033[0m ] Введите Ваш уникальный ключ от UserGate: "
   read  key
   key=$(tr -d ' ' <<< $key)
   #echo ${key}
   perl -MMIME::Base64 -e 'print encode_base64("'${key}'");' > ${File}
else
   read key < ${File}
   key=$(perl -MMIME::Base64 -e 'print decode_base64("'${key}'");')
fi
#echo ${key}
unset Password
if read -t 0 ; then        # Вызов из keepass
   read Password
else
   prompt="Введите Ваш корпоративный пароль: "
   while IFS= read -p "$prompt" -r -s -n 1 char ;do
      [[ $char == $'\0' ]] && break
      prompt='*'
      Password+="$char"
   done
fi
i=0
while true ; do
   (( 23 > (( $(date +%_S) % 30 )) )) && break
   (( 0 == ${i} )) && echo -en "\nОжидаем не более 7 секунд до получения нового OneTimePassword: "
   echo -n " $((( i++ )))"
   sleep 1
done
echo
date
OneTimePassword=$(oathtool -b --totp ${key})
#echo "<<<$Password:$OneTimePassword>>>"
sudo RTI_VPN nmcli <<< $Password:$OneTimePassword
ret=$?
[ 0 != ${ret}    ] && {
cat <<EOL
   Возможные причины:
   - Неправильно ввели QR код
   - Неправильно ввели пароль
   - Вы не в группе l2tp на  UserGate
   - Заблокирована Ваша сессия на UserGate
   - Оператор телефонной сети обрывает VPN
   - xl2tpd не запущен (systemctl status xl2tpd )
   - не отвечает https://sslvpn.npodr.ru:10443
EOL
   nc -zvw3 sslvpn.npodr.ru 10443 2>/dev/null
   [ 0 -ne $? ] && echo -e "   -Не отвечает sslvpn.npodr.ru\n"
   sudo RTI_VPN disconnect
   sleep 7
   return
}
kinit ${l2tpUSER} <<< $Password        # Получить билет для работы по керберос
sleep 3
}  ############################################################
f_nmcli(){             #   Активизировать RTI_VPN туннель
   IFS= read -r Password
   #echo "<<<$Password>>>"
   nmcli c up RTI_VPN --ask <<< $Password
}  ############################################################
f_clear(){             #   Удалить хранилище уникального ключа от UserGate
   rm -f ${File}
}  ############################################################
f_install(){           #   Установка SUDO и ярлыка desktop => sudo RTI_VPN install
[ ! -f /etc/sudoers.d/RTI_VPN ] && echo "ALL ALL=(ALL:ALL) NOPASSWD: /usr/local/bin/RTI_VPN" >/etc/sudoers.d/RTI_VPN
cat >/usr/local/Desktop/RTI_VPN.desktop <<EOL
[Desktop Entry]
Name=Доступ RTI_VPN
Name[ru]=Доступ RTI_VPN
Type=Application
NoDisplay=false
Exec=/usr/local/bin/RTI_VPN
Icon=security-policy
Icon[ru]=security-policy
Hidden=false
Path=/usr/local/bin/RTI_VPN
Terminal=true
StartupNotify=false
EOL
   f_ln RTI_VPN
}  ############################################################
f=$1
#set -x
[ 0 != $# ] && { shift ; f_${f} "$@" ; exit ;}
nmcli -f NAME con show --active | grep RTI_VPN
[ $? == 0 ] && { sudo RTI_VPN disconnect ; exit 0 ; }
f_connect
